// 非同期で取得
export const GET_LIST_REQUEST = "GET_LIST_REQUEST";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const GET_LIST_FAILURE = "GET_LIST_FAILURE";
export const POST_PRESEN_REQUEST = "POST_PRESEN_REQUEST";
export const POST_PRESEN_SUCCESS = "POST_PRESEN_SUCCESS";
export const POST_PRESEN_FAILURE = "POST_PRESEN_FAILURE";
export const GET_PRESEN_REQUEST = "GET_PRESEN_REQUEST";
export const GET_PRESEN_SUCCESS = "GET_PRESEN_SUCCESS";
export const GET_PRESEN_FAILURE = "GET_PRESEN_FAILURE";

